name: .NET Core Desktop

on:
  push:
    branches: [ "master", "actions-test" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore -c $env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MSIX Package
        path: ezRclone\bin\$env:Configuration\net6.0-windows
      
    - name: action-zip
      if: github.ref_name == 'master'
      uses: montudor/action-zip@v1.0.0
      with:
        args: zip -qq -r ezRclone-${{ steps.tag_version.outputs.new_tag }}.zip ezRclone\bin\$env:Configuration\net6.0-windows
      env:
        Configuration: ${{ matrix.configuration }}
      
    - name: Publish a release
      if: github.ref_name == 'master'
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          ezRclone-${{ steps.tag_version.outputs.new_tag }}.zip
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
